jobs:
  codeql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: CodeQL Bundle
        uses: advanced-security/codeql-bundle-action@v1.1.0
        with:
          bundle-version: ""
          packs: ""
          workspace: "."
          upload: true
          token: ${{ secrets.GITHUB_TOKEN }}
          concurrency-limit: 2
