name: Manual AI Review for External PR

on:
  pull_request:
   types: [opened, reopened]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (to get ai_review.py)
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies (latest OpenAI SDK)
        run: |
          pip install --upgrade pip
          pip install openai PyGithub

      - name: Run AI Review Script for External PR
        run: python .github/scripts/ai_review.py
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          PAT_REPO_B: ${{ secrets.PAT_REPO_B }}
          TARGET_REPO: 'dhanshreebornak/JavaSample'
          TARGET_PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: Enable debug logging
        run: |
          echo "Enabling debug logging..."
          echo "##[debug]Debug logging enabled"
