- name: OpenAI ChatGPT Code Review
  # You may pin to the exact commit or the version.
  # uses: adshao/chatgpt-code-review-action@a94b620b030d6ecd8f1c8355c9750db8e61b9351
  uses: adshao/chatgpt-code-review-action@v0.2.5
  with:
    # The programming language used in the GitHub repository. If not provided, the detected programming language will be used.
    PROGRAMMING_LANGUAGE: # optional, default is 
    # The comment to trigger a code review for the pull request.
    FULL_REVIEW_COMMENT: # optional, default is chatgpt
    # The comment prefix to trigger a code review with the comment content.
    REVIEW_COMMENT_PREFIX: # optional, default is chatgpt:
    # The API token for the OpenAI ChatGPT API.
    OPENAI_TOKEN: 
    # The API token for the Github API.
    GITHUB_TOKEN: 
    # The base URL for the GitHub API.'
    GITHUB_BASE_URL: # optional
    # The maximum code length for the pull request to be sent to OpenAI.
    MAX_CODE_LENGTH: # optional, default is 6000
    # The template for the FULL_REVIEW_COMMENT prompt.
    PROMPT_TEMPLATE: # optional, default is Please analyze the pull request's code and inform me whether it requires optimization, and provide an explanation for your decision:

\`\`\` ${code} \`\`\`
    # The template for the answer sent to the GitHub comment.
    ANSWER_TEMPLATE: # optional, default is AI Code Review:

${answer}
          
